version: '3.9'

services:   
  app-go:
    hostname: app-go
    container_name: app-go
    image: cosmtrek/air
    restart: unless-stopped
    command: ["-c", "/app/docker/.air.toml"]
    working_dir: /app
    ports:
      - ${DOCKER_PORT}:80
    environment:
      DB_DSN: ${DB_DSN}
    volumes:
      - ../:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"